# Generated by Django 4.2.21 on 2025-05-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nhs_number', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('patient_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_tablet', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('number_of_tablets', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('daily_dose', models.CharField(max_length=100)),
                ('side_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('further_info', models.TextField(blank=True, null=True)),
                ('storage_advice', models.CharField(max_length=100)),
                ('driving_using_machine', models.CharField(blank=True, max_length=100, null=True)),
                ('how_to_use_medication', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital_app.patient')),
            ],
        ),
    ]
